// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/user.proto

package nebula

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerExecutor_ExecuteStep_FullMethodName = "/nebula.WorkerExecutor/ExecuteStep"
)

// WorkerExecutorClient is the client API for WorkerExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerExecutorClient interface {
	ExecuteStep(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error)
}

type workerExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerExecutorClient(cc grpc.ClientConnInterface) WorkerExecutorClient {
	return &workerExecutorClient{cc}
}

func (c *workerExecutorClient) ExecuteStep(ctx context.Context, in *StepRequest, opts ...grpc.CallOption) (*StepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepResponse)
	err := c.cc.Invoke(ctx, WorkerExecutor_ExecuteStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerExecutorServer is the server API for WorkerExecutor service.
// All implementations must embed UnimplementedWorkerExecutorServer
// for forward compatibility.
type WorkerExecutorServer interface {
	ExecuteStep(context.Context, *StepRequest) (*StepResponse, error)
	mustEmbedUnimplementedWorkerExecutorServer()
}

// UnimplementedWorkerExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerExecutorServer struct{}

func (UnimplementedWorkerExecutorServer) ExecuteStep(context.Context, *StepRequest) (*StepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStep not implemented")
}
func (UnimplementedWorkerExecutorServer) mustEmbedUnimplementedWorkerExecutorServer() {}
func (UnimplementedWorkerExecutorServer) testEmbeddedByValue()                        {}

// UnsafeWorkerExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerExecutorServer will
// result in compilation errors.
type UnsafeWorkerExecutorServer interface {
	mustEmbedUnimplementedWorkerExecutorServer()
}

func RegisterWorkerExecutorServer(s grpc.ServiceRegistrar, srv WorkerExecutorServer) {
	// If the following call pancis, it indicates UnimplementedWorkerExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerExecutor_ServiceDesc, srv)
}

func _WorkerExecutor_ExecuteStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerExecutorServer).ExecuteStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerExecutor_ExecuteStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerExecutorServer).ExecuteStep(ctx, req.(*StepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerExecutor_ServiceDesc is the grpc.ServiceDesc for WorkerExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebula.WorkerExecutor",
	HandlerType: (*WorkerExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteStep",
			Handler:    _WorkerExecutor_ExecuteStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
